# -*- coding: utf-8 -*-
"""Basic RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IdBjgCdNLuiVpRYx0_czFWPUPyR-dVWN
"""

pip install pypdf chromadb -U sentence-transformers --upgrade transformers nltk -U langchain-experimental langchain-huggingface pinecone

"""1. Extracting the PDFs."""

from pypdf import PdfReader

document = PdfReader('story1.pdf')
text = ""
print(document.pages)
for page in document.pages:
  text += page.extract_text() or ""
  text += "\n"
print(text)

"""Text chunking

"""

from typing import List
import re

def word_splitter(source_text: str) -> List[str]:
    # Replace multiple whitespaces with a single space
    source_text = re.sub(r'\s+', ' ', source_text)
    # Split text by single whitespace
    return re.split(r'\s', source_text)

def get_chunks_fixed_size(text: str, chunk_size: int) -> List[str]:
    text_words = word_splitter(text)
    chunks = []
    for i in range(0, len(text_words), chunk_size):
        chunk_words = text_words[i: i + chunk_size]
        chunk = ' '.join(chunk_words)
        chunks.append(chunk)
    return chunks

def get_chunks_fixed_size_with_overlap(text: str, chunk_size: int, overlap_fraction: float) -> List[str]:
    text_words = word_splitter(text)
    overlap_int = int(chunk_size * overlap_fraction)
    stride = chunk_size - overlap_int # The jump size

    chunks = []
    # Loop by the stride, not the chunk_size
    for i in range(0, len(text_words), stride):
        chunk_words = text_words[i : i + chunk_size]
        chunk = ' '.join(chunk_words)
        chunks.append(chunk)

        # Break if we've reached the end of the text
        if i + chunk_size >= len(text_words):
            break

    return chunks

chunks = get_chunks_fixed_size_with_overlap(text, 300, 0.3)
print(chunks[0])
print(len(chunks))

"""sentence based chunking

"""

import nltk

nltk.download('punkt_tab')

from nltk.tokenize import sent_tokenize

chunks = sent_tokenize(text)
print(chunks)

"""initializing the model for embedding and semantic chunking"""

from sentence_transformers import SentenceTransformer

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

"""Semantic chunking

"""

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_experimental.text_splitter import SemanticChunker

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

semantic_chunker = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="percentile"
)

semantic_chunks = semantic_chunker.create_documents([text])

print(f"Number of chunks: {len(semantic_chunks)}")

for chunk in semantic_chunks[:3]:
    print(chunk.page_content)
    print("-" * 50)

"""Loading the embedding model

"""

texts = [doc.page_content for doc in semantic_chunks]

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
embeddings = model.encode(texts)
print(embeddings.shape)
similarities = model.similarity(embeddings, embeddings)

"""Storing the embeddings in vector DB


"""

import chromadb

client = chromadb.PersistentClient(path="my_vectordb")
collection = client.get_or_create_collection(
    name="story_collection_new_smeantic_chunk"
)

collection.add(
    ids=[str(i) for i in range(len(texts))],
    documents=texts,
    embeddings=embeddings.tolist()
)

def similarity_search(collection, query_text, top_k=3):
    query_embedding = model.encode(query_text)

    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=top_k
    )

    return results

"""using a Pinecone DB to store the embeddings vector"""

from pinecone import Pinecone, ServerlessSpec

pc = Pinecone(
    api_key="************************************"
)

index_name = "long-story-db"

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384,
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws",
            region="us-east-1"
        )
    )

index = pc.Index(index_name)

vectors = []

for i, (text, emb) in enumerate(zip(texts, embeddings)):
    vectors.append({
        "id": str(i),
        "values": emb.tolist(),
        "metadata": {
            "text": text
        }
    })

index.upsert(vectors=vectors)

def similarity_search(query_text, top_k=3):

    query_embedding = model.encode(query_text)

    results = index.query(
        vector=query_embedding.tolist(),
        top_k=top_k,
        include_metadata=True
    )

    return results

"""Loading the QA Model QWEN

"""

import torch
from transformers import pipeline

model_id = "Qwen/Qwen2.5-3B-Instruct"

pipe = pipeline(
    "text-generation",
    model=model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

"""Prompting the LLM with query

"""

question = "How old is Daniel?"

# Retrieve relevant chunks
results = similarity_search(
    question
)

context = "\n".join(
    match.metadata["text"]
    for match in results.matches
)

# Build prompt using retrieved context
prompt = f"""
You are a question answering system.

Use ONLY the provided context.

If the answer is present in the context:
Return ONLY the answer.

If the answer is not present in the context:
Return EXACTLY:
The retrieved context is not relevant to answer this question.


Context:
{context}

Question:
{question}

Answer:
"""

# Generate answer
response = pipe(
    prompt,
    max_new_tokens=100,
    do_sample=False
)

print(response[0]["generated_text"])

"""FAST API Tunelling"""

!pip install -q fastapi uvicorn nest_asyncio transformers accelerate

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# from fastapi import FastAPI
# from pydantic import BaseModel
# 
# app = FastAPI()
# 
# # These will be assigned from the notebook
# pipe = None
# embedding_model = None
# index = None
# 
# 
# class Prompt(BaseModel):
#     prompt: str
# 
# 
# @app.get("/")
# def home():
#     return {"status": "Server is running"}
# 
# 
# def similarity_search(query_text, top_k=5):
#     query_embedding = embedding_model.encode(query_text)
# 
#     results = index.query(
#         vector=query_embedding.tolist(),
#         top_k=top_k,
#         include_metadata=True
#     )
# 
#     return results
# 
# 
# @app.post("/generate")
# def generate(data: Prompt):
# 
#     if pipe is None:
#         return {"error": "LLM not loaded"}
# 
#     if embedding_model is None:
#         return {"error": "Embedding model not loaded"}
# 
#     if index is None:
#         return {"error": "Pinecone index not loaded"}
# 
#     # -------------------------
#     # Retrieve relevant chunks
#     # -------------------------
#     results = similarity_search(data.prompt)
# 
#     context = "\n\n".join(
#         match.metadata["text"]
#         for match in results.matches
#     )
# 
#     # -------------------------
#     # Build prompt
#     # -------------------------
#     prompt = f"""
# You are a RAG question answering assistant.
# 
# Answer ONLY from the retrieved context.
# 
# If the answer cannot be found in the context, reply exactly:
# 
# I don't know.
# 
# Retrieved Context:
# {context}
# 
# Question:
# {data.prompt}
# 
# Answer:
# """
# 
#     # -------------------------
#     # Generate answer
#     # -------------------------
#     output = pipe(
#         prompt,
#         max_new_tokens=80,
#         do_sample=False,
#         return_full_text=False
#     )
# 
#     answer = output[0]["generated_text"].strip()
# 
#     return {
#         "question": data.prompt,
#         "answer": answer,
#         "retrieved_context": context
#     }

import importlib
import app

importlib.reload(app)

app.pipe = pipe
app.embedding_model = model
app.index = index

import nest_asyncio
import uvicorn
import threading

nest_asyncio.apply()

config = uvicorn.Config(
    app.app,
    host="0.0.0.0",
    port=8000,
    log_level="info"
)

server = uvicorn.Server(config)

thread = threading.Thread(target=server.run, daemon=True)
thread.start()

import requests

requests.get("http://127.0.0.1:8000").json()

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

import subprocess
import re
import time

process = subprocess.Popen(
    [
        "./cloudflared-linux-amd64",
        "tunnel",
        "--url",
        "http://localhost:8000"
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

while True:
    line = process.stdout.readline()
    print(line, end="")
    match = re.search(r"https://[-a-zA-Z0-9]+\.trycloudflare\.com", line)
    if match:
        public_url = match.group(0)
        break

print("\nPublic URL:", public_url)

print(index.describe_index_stats())

results = similarity_search("How old is Daniel?", top_k=3)

for i, match in enumerate(results.matches):
    print("=" * 80)
    print(f"MATCH {i+1}")
    print("Score:", match.score)
    print("Text:")
    print(match.metadata["text"])